### ISSUE TITLE
`Question` How to use local module written in es6

### ISSUE THREAD

**Issue by havenchyk** [rauschma/babel-on-node#1]
Hi Alex,

I'd like to use your example and publish my useful :smile: package to npm. The structure is the same as in this repository, but there is also module `src/myModule.es6.js` and I'd like to import it inside `Point.js`. I'd like to transpile it before the publishing, could you suggest any solution here? 

Thanks in advance,
Uladzimir

**Comment by rauschma** [comment]
This may help: https://github.com/rauschma/node-es6-demo

Otherwise, check the Babel docs, they are quite good!

**Comment by havenchyk** [comment]
@rauschma thanks for quick response, yes, I've checked this repo before and still have same question.

I can't realize, how to make correct import before and after transpiling. 

e.g. I have my structure

/root
      index.es6.js (import myModule here)
      /src
        myModule.es6.js

And after compiling to a es5 files I haven't correct path to myModule.js. Do you see any error here or how to solve this? 

I'd like to put index.es5.js near index.es6.js and myModule.es5.js wherever.

ps.
Ahh, I see you've closed this issue. Sorry for disturbing in this case.
